package com.rbanerjee.SmartSabzi.Entity;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UuidGenerator;

import java.time.Instant;
import java.util.UUID;

@Entity
@Data
@Table(
        name = "offline_sync_log",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"vendor_id", "local_sale_id"})
        }
)
public class OfflineSyncLog {

    @Id
    @Column
    @GeneratedValue
    @UuidGenerator
    private UUID syncId;

    // Which vendor performed the sync
    @JoinColumn(name = "vendor_id", nullable = false)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Vendor vendor;

    // The local ID generated by mobile app
    @Column(nullable = false)
    private String localSaleId;

    // The real Sale created on server
    @JoinColumn(name = "server_sale_id", nullable = false)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Sale serverSale;

    // When sync happened
    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant syncedAt;
}
